"""
Notion color constants.
"""
from notion_database.const.color import (
    BLUE,
    BLUE_BACKGROUND,
    BROWN,
    BROWN_BACKGROUND,
    DEFAULT,
    GRAY,
    GRAY_BACKGROUND,
    GREEN,
    GREEN_BACKGROUND,
    ORANGE,
    ORANGE_BACKGROUND,
    PINK,
    PINK_BACKGROUND,
    PURPLE,
    PURPLE_BACKGROUND,
    RED,
    RED_BACKGROUND,
    YELLOW,
    YELLOW_BACKGROUND,
)

__all__ = [
    "DEFAULT",
    "GRAY",
    "BROWN",
    "ORANGE",
    "YELLOW",
    "GREEN",
    "BLUE",
    "PURPLE",
    "PINK",
    "RED",
    "GRAY_BACKGROUND",
    "BROWN_BACKGROUND",
    "ORANGE_BACKGROUND",
    "YELLOW_BACKGROUND",
    "GREEN_BACKGROUND",
    "BLUE_BACKGROUND",
    "PURPLE_BACKGROUND",
    "PINK_BACKGROUND",
    "RED_BACKGROUND",
]
