[tox]
minversion = 4.0
envlist = py310, py311, py312, py313, lint
isolated_build = true

[testenv]
deps = pytest
commands =
    pytest -v

[testenv:lint]
deps = pylint
commands =
    pylint -rn notion_database
